# -*- coding: utf-8 -*-
"""antigravity_urea.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17OJC-wwxmPdWJ9n2NeH1-lB1MBewavtE
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta

class PhysicalAsset:
    """
    PhysicalAsset (The Field):
    Stores soil parameters and confidence scores.
    Defaults represent the Argentine Pampa Húmeda.
    """
    def __init__(self, ph=6.5, texture='Silty Loam', cec=25):
        self.ph = ph
        self.texture = texture
        self.cec = cec
        self.confidence_score = 0.5

    def sync_sensors(self, sensor_data=None):
        """
        Updates parameters from ground sensors and increases confidence.
        """
        if sensor_data:
            if 'ph' in sensor_data:
                self.ph = sensor_data['ph']
            if 'texture' in sensor_data:
                self.texture = sensor_data['texture']
            if 'cec' in sensor_data:
                self.cec = sensor_data['cec']
        self.confidence_score = 0.95

class DataStreamManager:
    """
    DataStreamManager (Time Series):
    Manages weather forecasts and satellite proxies.
    """
    def __init__(self):
        self.forecast_df = pd.DataFrame()
        self.satellite_proxy = None

    def load_forecast(self, data):
        """
        Expects a list of dicts or dict of lists for a 5-day forecast containing:
        [Temperature, Wind_Speed, Humidity, Rainfall_mm]
        """
        self.forecast_df = pd.DataFrame(data)

    def update_satellite_proxy(self, ndvi_trends):
        """
        Stores simulated NDVI trends.
        """
        self.satellite_proxy = ndvi_trends

class StandardUreaModel:
    """
    StandardUreaModel (Mechanistic Brain):
    Calculates risks and enforces safety 'Gatekeepers'.
    """
    def __init__(self, physical_asset: PhysicalAsset):
        self.asset = physical_asset

    def check_gatekeepers(self, temp, wind, rainfall):
        """
        Enforces the 'Instant NO' List.
        Returns (is_blocked, reason_message)
        """
        if wind > 25:
            return True, "BLOCK: Wind > 25km/h (High Volatilization/Drift)"
        if rainfall > 60:
            return True, "BLOCK: Rain > 60mm (Washout/Leaching Risk)"
        if rainfall < 5:
            return True, "BLOCK: Rain < 5mm (Not enough water)"
        if temp > 28:
            return True, "BLOCK: Temp > 28°C (Uncontrollable Loss)"

        return False, ""

    def calculate_volatilization_risk(self, temp, wind, humidity):
        """
        Calculates the volatilization risk flux.
        Restructured: Wind acts as a synergistic multiplier for Temperature.
        """
        # 1. HUMIDITY NORMALIZATION (Inverse linear remains as requested)
        norm_h = humidity / 100.0 if humidity > 1.0 else humidity
        norm_h = max(min(norm_h, 1.0), 0.05)
        dryness_factor = 1.0 - norm_h

        # 2. CLIMATE SYNERGY (Geometric Relationship)
        # We treat Temperature as the 'Engine' and Wind as the 'Accelerator'.
        # A base wind factor of 1.0 ensures risk doesn't drop to zero on calm days.
        wind_multiplier = 1.0 + (wind * 0.05)  # Slight scaling to prevent runaway spikes
        climate_impact = (temp * 0.50) * wind_multiplier

        # 3. WEIGHTED SCORING
        # Dryness remains an additive 'Vulnerability' factor.
        dry_impact = dryness_factor * 20.0

        base_risk = climate_impact + dry_impact

        # 4. CHEMICAL CATALYST
        if self.asset.ph > 7.5:
            base_risk *= 1.25

        return base_risk * 0.5

    def calculate_incorporation_score(self, rainfall):
            """
            Calculates urea incorporation efficiency based on rainfall (in mm).
            Returns a float between 0.1 (severe loss) and 1.0 (perfect incorporation).
            """
            # 1. The Trap: Not enough water to bury it, triggers volatilization.
            if rainfall < 5:
                return 0.1

            # 2. The Climb: Linear increase as water volume becomes sufficient to wash N in.
            if 5 <= rainfall < 15:
                return 0.1 + 0.9 * ((rainfall - 5) / 10.0)

            # 3. The Sweet Spot: Maximum efficiency. Soil sponge holds all water in root zone.
            if 15 <= rainfall <= 35:
                return 1.0

            # 4. The Saturation Bend: Sponge getting full, N pushed slightly deep.
            # Drops linearly from 1.0 to 0.85.
            if 35 < rainfall <= 45:
                return 1.0 - 0.15 * ((rainfall - 35) / 10.0)

            # 5. The Washout Curve: Soil exceeds field capacity.
            # Loss accelerates as rainfall increases. Drops smoothly from 0.85 to 0.1.
            if 45 < rainfall <= 80:
                # Calculate progress through this 35mm hazard zone (0.0 to 1.0)
                progress = (rainfall - 45) / 35.0

                # Squaring the progress creates a smooth, accelerating downward curve.
                # Total drop possible in this phase is 0.75 (from 0.85 down to 0.10).
                return 0.85 - 0.75 * (progress ** 2)

            # 6. Total Washout: Severe storm. Massive runoff and deep leaching.
            return 0.1

    def calculate_leaching_risk(self, rainfall):
        return (rainfall - 35) / 10.0 if rainfall > 35 else 0.0

class OptimizationEngine:
    def __init__(self, model: StandardUreaModel):
        self.model = model

    def get_viability_index(self, forecast_df):
        """
        Calculates 0-100% Viability.
        Gatekeepers force 0% regardless of other data.
        """
        # Define Global Ideal Raw Score for normalization (10°C, 0km/h wind, 60% Hum, 20mm Rain)
        ideal_vol = self.model.calculate_volatilization_risk(10, 0, 60)
        ideal_inc = self.model.calculate_incorporation_score(20)
        ideal_raw = ideal_inc - (ideal_vol * 0.01) # Scaled for benchmark

        results = []
        for _, row in forecast_df.iterrows():
            # 1. CHECK GATEKEEPERS FIRST
            is_blocked, reason = self.model.check_gatekeepers(
                row['Temperature'], row['Wind_Speed'], row['Rainfall_mm']
            )

            if is_blocked:
                viability = 0.0
                status = reason
                vol_risk = self.model.calculate_volatilization_risk(
                    row['Temperature'], row['Wind_Speed'], row['Humidity']
                )
                leach_risk = self.model.calculate_leaching_risk(row['Rainfall_mm'])
                print(f"BLOCKED: {reason}")
            else:
                # 2. PROCEED WITH MECHANISTIC SCORING
                vol_risk = self.model.calculate_volatilization_risk(
                    row['Temperature'], row['Wind_Speed'], row['Humidity']
                )
                inc_score = self.model.calculate_incorporation_score(row['Rainfall_mm'])
                leach_risk = self.model.calculate_leaching_risk(row['Rainfall_mm'])

                raw_score = inc_score - (vol_risk * 0.01) - leach_risk
                viability = max(0, min(100, (raw_score / ideal_raw) * 100))
                status = "OK" if viability > 60 else "LOW EFFICIENCY"

            results.append({
                'Date': row.get('Date', 'Forecast Day'),
                'Viability_%': round(viability, 1),
                'Status': status,
                'Wind': row['Wind_Speed'],
                'Rain': row['Rainfall_mm'],
                'Volatilization_Risk': round(vol_risk, 2), # Add Volatilization Risk
                'Leaching_Risk': round(leach_risk, 2)     # Add Leaching Risk
            })

        return pd.DataFrame(results)

class TwinRefiner:
    """
    LearningInterface (ML Placeholder):
    Placeholder for future machine learning adjustments.
    """
    def __init__(self):
        pass

    def calculate_residual_error(self, predicted_loss, ndvi_trend):
        """
        Documented function where a future Random Forest model will adjust
        the physical constants of the StandardUreaModel based on
        the difference between prediction and actual observed proxy (NDVI).
        """
        # Simplified placeholder calculation
        actual_loss_proxy = 1.0 - ndvi_trend
        residual = abs(predicted_loss - actual_loss_proxy)
        return residual

def main():
    print("--- Modular Digital Twin Engine for Urea Application ---")

    # 1. Initialize the Field (PhysicalAsset)
    field = PhysicalAsset()
    print(f"[Field Initialization] Defaults: pH={field.ph}, Texture={field.texture}, CEC={field.cec}")
    print(f"[Confidence Score] {field.confidence_score} (Uncalibrated)")

    # Simulate ground sensor connection
    print("\nConnecting ground sensors...")
    field.sync_sensors({'ph': 7.6}) # High pH triggers volatilization penalty
    print(f"[Confidence Score] {field.confidence_score} (Calibrated)")
    print(f"[Updated Parameters] pH={field.ph}")

    # 2. Manage Data Streams
    stream_manager = DataStreamManager()

    # Simulate 5-day forecast
    base_date = datetime.now().date()
    dates = [base_date + timedelta(days=i) for i in range(5)]
    mock_forecast = {
        'Date': dates,
        'Temperature': [22, 15, 28, 18, 25],  # Celsius
        'Wind_Speed': [15, 0,  25, 10, 20],   # km/h (0 for ideal comparison)
        'Humidity': [60, 50, 40, 70, 50],     # %
        'Rainfall_mm': [0, 15, 2,  40, 5]     # mm (20mm is ideal)
    }

    stream_manager.load_forecast(mock_forecast)
    stream_manager.update_satellite_proxy([0.8, 0.85, 0.75, 0.9, 0.78])

    # 3. Model & Optimize
    urea_model = StandardUreaModel(field)
    optimizer = OptimizationEngine(urea_model)

    results_df = optimizer.get_viability_index(stream_manager.forecast_df)

    # Display the results
    display_df = pd.merge(stream_manager.forecast_df, results_df, on='Date')
    print("\n--- 5-Day Evaluation ---")
    print(display_df[['Date', 'Temperature', 'Wind_Speed', 'Rainfall_mm', 'Viability_%']].to_string(index=False))

    # 4. Final Recommendation
    best_day_idx = results_df['Viability_%'].idxmax()
    best_day = results_df.iloc[best_day_idx]
    max_viability = best_day['Viability_%']

    print("\n--- Recommendation Engine ---")
    if max_viability >= 80:
        print(f" prodigious APPLY NOW! Best window is on {best_day['Date']} ({max_viability:.1f}% viability) <<<")
    elif max_viability >= 50:
        print(f" prodigious WAIT. Suboptimal conditions. Best day is {best_day['Date']} ({max_viability:.1f}%), wait for a better window. <<<")
    else:
        print(" prodigious HIGH RISK. Do not apply in the next 5 days due to poor conditions. <<<")
     # 5. Build the Dashboard (Matplotlib)
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 10))

    # Subplot 1: Viability % Curve
    ax1.plot(results_df['Date'], results_df['Viability_%'], marker='o', linestyle='-', color='#2ca02c', linewidth=2.5)
    ax1.set_title('5-Day Application Viability Index', fontsize=14, pad=15)
    ax1.set_ylabel('Viability (%)', fontsize=12)
    ax1.set_ylim(0, 105)
    ax1.grid(True, linestyle='--', alpha=0.6)
    ax1.axhline(100, color='#1f77b4', linestyle='--', label='Global Agronomic Ideal')
    ax1.legend()

    # Subplot 2: Risk Stacked Bar
    dates_str = [d.strftime('%Y-%m-%d') for d in results_df['Date']]
    # Safely get risk columns, providing defaults if they are not present
    vol_risks = results_df.get('Volatilization_Risk', [0.0] * len(results_df))
    leach_risks = results_df.get('Leaching_Risk', [0.0] * len(results_df))

    # Normalize risks for better visualization stacked next to each other
    ax2.bar(dates_str, vol_risks, label='Volatilization Risk', color='#ff7f0e', alpha=0.8)
    ax2.bar(dates_str, leach_risks, bottom=vol_risks, label='Leaching Risk', color='#d62728', alpha=0.8)

    ax2.set_title('Risk Profile: Volatilization vs Leaching', fontsize=14, pad=15)
    ax2.set_ylabel('Relative Risk Score', fontsize=12)
    ax2.grid(True, axis='y', linestyle='--', alpha=0.6)
    ax2.legend()

    plt.tight_layout()
    plt.savefig('urea_dashboard.png', dpi=300)
    print("\nDashboard successfully saved as 'urea_dashboard.png'.")
    print("(Note: In Google Colab, use plt.show() to view this dashboard inline.)")

if __name__ == "__main__":
    main()